language: java
jdk:
  - oraclejdk8
install:
  - curl https://sh.rustup.rs -sSf -m 60 | sh -s -- -y -v --default-toolchain nightly
  - rustup target add wasm32-unknown-unknown --toolchain nightly
  - rustup run nightly rustc --version --verbose
  - rustup run nightly cargo --version --verbose
  - cd rust
  - rustup run nightly cargo build
  - cd ..
script:
  - bash gradlew displayCommitHash
  - bash gradlew isCI
  - bash gradlew buildPlugin
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/