language: java
jdk:
  - oraclejdk8
before_install:
  - curl https://sh.rustup.rs -sSf -m 60 | sh -s -- -y -v --default-toolchain nightly
  - source $HOME/.cargo/env
  - rustup target add wasm32-unknown-unknown --toolchain nightly
  - rustup run nightly rustc --version --verbose
  - rustup run nightly cargo --version --verbose
install:
  - cd rust
  - rustup run nightly cargo build --release
  - cd ..
script:
  - bash gradlew displayCommitHash
  - bash gradlew isCI
  - bash gradlew test
  - bash gradlew verifyPlugin
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
