language: java
jdk:
  - oraclejdk8
before_install:
  - curl https://sh.rustup.rs -sSf -m 60 | sh -s -- -y -v --default-toolchain nightly
  - source $HOME/.cargo/env
  - rustup target add wasm32-unknown-unknown --toolchain nightly
  - rustup run nightly rustc --version --verbose
  - rustup run nightly cargo --version --verbose
install:
  - rustup run nightly cargo install --git https://github.com/alexcrichton/wasm-gc
script:
  - bash gradlew displayCommitHash isCI test verifyPlugin --info --no-daemon
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/