os: Visual Studio 2017

environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
#

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - appveyor DownloadFile https://github.com/cretz/asmble/releases/download/0.4.0/asmble-0.4.0.zip
  - 7z e -y asmble-0.4.0.zip
  - ./asmble-0.4.0/asmble/bin/asmble --help
  - rustup-init -yv --default-toolchain nightly
  - refreshenv
  - rustup target add wasm32-unknown-unknown --toolchain nightly
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

build_script:
  - cd rust
  - cargo build --release
  - cd ..
  - gradlew displayCommitHash
  - gradlew buildPlugin --info
  - gradlew verifyPlugin --info
#

cache:
  - C:\Users\appveyor\.gradle

artifacts:
  - path: 'build\distributions\*.zip'
    name: intellij-pest
#
