os: Visual Studio 2019

environment:
  JAVA_HOME: C:\Program Files\Java\jdk11
  JDK_HOME: C:\Program Files\Java\jdk11
  JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
#

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain nightly
  - refreshenv
  - rustup target add wasm32-unknown-unknown --toolchain nightly
  - set PATH=%JDK_HOME%\bin;%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV
  - cargo install --git https://github.com/alexcrichton/wasm-gc

build_script:
  - gradlew displayCommitHash buildPlugin --info
  - gradlew verifyPlugin --info
#

cache:
  - C:\Users\appveyor\.gradle

artifacts:
  - path: 'build\distributions\*.zip'
    name: intellij-pest
#
