name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install Nightly Rustfmt
        run: rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu
      - name: Install Nightly Clippy
        run: rustup component add clippy --toolchain nightly-x86_64-unknown-linux-gnu
      - uses: pre-commit/action@v2.0.2
